name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup bun cache
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-store-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-store-

      - name: Install dependencies
        run: bun install

        # use astro check for issues
      - name: Run check
        run: bun run check

        # ensure build works
      - name: Run build
        run: bun run build
